# Generated by Django 6.0 on 2026-01-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_director_remove_movie_genre_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, help_text='Movie poster image (optional)', null=True, upload_to='movies/posters/'),
        ),
    ]
