# Generated by Django 6.0 on 2026-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, help_text='Movie plot synopsis (optional)', null=True),
        ),
    ]
