# Generated by Django 6.0 on 2026-01-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (optional)', null=True, upload_to='users/profiles/'),
        ),
    ]
