# Generated by Django 6.0 on 2026-03-02 19:02

from django.db import migrations



def create_moderators_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(id=1, name='Moderators')

def remove_moderators_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(id=1, name='Moderators').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_picture'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_moderators_group, reverse_code=remove_moderators_group),
    ]
